name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    name: Generate project

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        syntax: [OCaml, Reason]
        package-manager: [Opam, Esy]

    env:
      SPIN_PROJECT_NAME: Demo
      SPIN_CREATE_SWITCH: false
      SPIN_AUTHOR_NAME: Jonh Doe
      SPIN_INCLUDE_TAILWIND: ${{ matrix.tailwind == 'tailwind' }}
      SPIN_INCLUDE_EMBEDDED_JS: ${{ matrix.embedded-js == 'embedded-js' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ocaml-base-compiler.4.12.0
        uses: ocaml/setup-ocaml@master
        with:
          ocaml-compiler: ocaml-base-compiler.4.12.0

      - run: opam install spin

      - run: opam exec -- spin new . _generated -d -vv

      - run: make test
        working-directory: _generated
        if: ${{ matrix.package-manager == 'Opam' }}

      - run: esy test
        working-directory: _generated
        if: ${{ matrix.package-manager == 'Esy' }}
